@startuml
' Definizioni delle Classi
class Libro {
  -isbn: String 
  -titolo: String 
  -autore: List<String> 
  -anno: int 
  -copieTotali: int 
  -copieDisponibili: int 
  +Libro(isbn: String, titolo: String, autore: List<String>, anno: int, copieTotali: int)
  +getISBN(): String
  +getTitolo(): String
  +getAutore(): List<String>
  +getCopieTotali(): int
  +getAnno(): int
  +getCopieDisponibili(): int
  +incrementaDisponibilita(): void
  +decrementaDisponibilita(): void
  +isDisponibile(): boolean
}

class Utente {
  -matricola: String 
  -nome: String 
  -cognome: String 
  -email: String 
  -prestitiAttivi: List<Prestito>
  +Utente(matricola: String, nome: String, cognome: String, email: String)
  +getEmail(): String
  +getMatricola(): String
  +getCognome(): String
  +getNome(): String
  +getNumeroPrestitiAttivi(): String
  +getPrestitiAttivi(): List<Prestito>
  +aggiungiPrestito(p: Prestito): void
  +rimuoviPrestito(p: Prestito): void
  +verificaLimite(max: int): boolean
}

class Prestito {
  -idPrestito: int
  -libro: Libro 
  -utente: Utente 
  -dataInizio: LocalDate 
  -dataPrevistaRestituzione: LocalDate 
  -dataEffettivaRestituzione: LocalDate 
  -inRitardo: boolean
  +Prestito(idPrestito: int, libro: Libro, utente: Utente, dataInizio: LocalDate, dataPrevistaRestituzione: LocalDate)
  +getIdPrestito(): int
  +getLibro(): Libro
  +getUtente(): Utente
  +getDataInizio(): LocalDate
  +getDataPrevistaRestituzione(): LocalDate
  +getDataEffettivaRestituzione(): LocalDate
  +chiudiPrestito(dataEffettiva: LocalDate): void
  +verificaRitardo(): boolean
  +segnaRitardo(): void
}

class Catalogo {
  -registroLibri: Map<String, Libro> 
  +Catalogo()
  +aggiungiLibro(l: Libro): boolean
  +rimuoviLibro(isbn: String): boolean
  +modificaLibro(isbn: String, nl: Libro): boolean
  +getLibro(isbn: String): Libro
  +ricerca(query: String, campo: String): List<Libro>
  +visualizzaOrdinata(): List<Libro>
}

class Anagrafica {
  -registroUtenti: Map<String, Utente> 
  +Anagrafica()
  +aggiungiUtente(u: Utente): boolean
  +rimuoviUtente(matricola: String): boolean
  +modificaUtente(matricola: String, u: Utente): boolean
  +getUtente(matricola: String): Utente
  +cercaUtente(query: String, campo: String): List<Utente>
  +visualizzaOrdinata(): List<Utente>
}

class RegistroPrestiti {
  -catalogo: Catalogo 
  -anagrafica: Anagrafica
  -prestitiAttivi: List<Prestito> 
  -limitePrestiti: int 
  +RegistroPrestiti(catalogo: Catalogo, anagrafica: Anagrafica)
  +setCatalogo(catalogo: Catalogo): void
  +setAnagrafica(anagrafica: Anagrafica): void
  +registraPrestito(isbn: String, matr: String, dataPrev: LocalDate): Prestito
  +registraRestituzione(idPrestito: int, dataEff: LocalDate): boolean
  +getPrestitiAttivi(): List<Prestito>
  +getPrestitiAttivi(u: Utente): List<Prestito>
  +getPrestitiInRitardo(): List<Prestito>
  +haPrestitiAttivi(matricola: String): boolean
  +trovaPrestito(idPrestito: int): Prestito
}

class Credenziali{
    -user: String
    -password: String
    +Credenziali(user: String, password: String)
    +getUser(): String
    +getPassword(): String
}

class GUIController {
  -catalogo: Catalogo 
  -anagrafica: Anagrafica 
  -registro: RegistroPrestiti 
  -archivio: IArchivioDati
  -valida: ValidatoreDati
  -logger: ILogger
  -autenticatore: IAutenticatore
  -observableLog: ObservableList<String>
  +GUIController(archivio: IArchivioDati, logger: ILogger, autenticatore: IAutenticatore, catalogo: Catalogo, anagrafica: Anagrafica, registro: RegistroPrestiti, valida: ValidatoreDati)
  +scriviLog(messaggio: String): void
  +avviaSistema(): boolean
  +chiudiSistema(): boolean
  +aggiungiUtente(u: Utente): boolean
  +modificaUtente(matrOriginale: String, uNuovo: Utente): boolean
  +rimuoviUtente(matr: String): boolean
  +cercaUtente(query: String, campo: String): List<Utente>
  +ottieniAnagraficaOrdinato(): List<Utente>
  +aggiungiLibro(l: Libro): boolean
  +modificaLibro(isbnOriginale: String, lNuovo: Libro): boolean
  +rimuoviLibro(isbn: String): boolean 
  +cercaLibro(query: String, campo: String): List<Libro>
  +ottieniCatalogoOrdinato(): List<Libro>
  +gestisciPrestito(isbn: String, matr: String, dataPrevistaRestituzione: LocalDate): boolean
  +gestisciRestituzione(idPrestito: int, dataEffettivaRestituzione: LocalDate): boolean
  +ottieniReportPrestiti(): List<Prestito>
  +ottieniAuditTrail(): ObservableList<String>
  +gestisciLogin(user: String, pass: String): boolean
}

class GUIView{
   -sistema: GUIController
   -messaggi: MessaggiInterfaccia
   -primaryStage: Stage
   -datiAuditTrail: ObservableList<String>
   -dashboardController: DashboardController
   +GUIView(sistema: GUIController, primaryStage: Stage)
   +avviaInterfaccia(): void
   +stilaPulsantiDialogo(dialog: Dialog<?>): 
   +gestisciAggiuntaLibro(): void
   +gestisciAggiuntaUtente(): void
   +gestisciModificaLibro(): void
   +gestisciModificaUtente(): void
   +gestisciEliminazioneUtente(): void
   +gestisciEliminazioneLibro(): void
   +gestisciRegistrazionePrestito(): void
   +gestisciRestituzionePrestito(): void
   +gestisciRicercaLibro(): void
   +gestisciRicercaUtente(): void
   +mostraListaLibri(lista: List<Libro>): void
   +mostraListaUtenti(lista: List<Utente>: void
   +mostraListaPrestiti(lista: List<Prestito>): void
   +mostraListaAuditTrail(lista: List<String>): void
   +mostraReportUtente(u: Utente): void
   +mostraMessaggio(msg: Object): void
   +mostraFinestraLogin(): void
   +mostraLogDiSistema(log: List<String>): void
}

interface IArchivioDati{
   +salvaStato(dati: Object, nomeFile: String): boolean
   +caricaStato(nomeFile: String): Object
   +verificaEsistenzaFile(nomeFile: String): boolean
}

interface ILogger{
  +registraAzione(azione: String): void
  +caricaLog(): List<String>
  +salvaLog(): void
  +visualizzaLog(): List<String>
}

interface IAutenticatore{
   +verificaCredenziali(user: String, pass: String): boolean
}

class AuditTrail {
   -logRecords: List<String>
   -archivioDati: IArchivioDati
   +AuditTrail(logRecords: List<String>, archivio: IArchivioDati)
   +registraAzione(azione: String): void
   +caricaLog(): List<String>
   +salvaLog(): void
   +visualizzaLog(): List<String>
}

class FileArchivio {
  -pathDati: String
  -logger: ILogger
  +FileArchivio(path: String, logger: ILogger)
  +salvaStato(dati: Object, nomeFile: String): boolean
  +caricaStato(nomeFile: String): Object
  +verificaEsistenzaFile(nomeFile: String): boolean
}

class FileAutenticatore{
   -credentialsFile: String
   -archivioDati: IArchivioDati
   +FileAutenticatore(credentialsFile: String, archivioDati: Archivio)
   +verificaCredenziali(user: String, pass: String): boolean
}

class ValidatoreDati {
  +validaISBN(isbn: String): boolean
  +validaMatricola(matr: String): boolean
  +validaEmail(email: String): boolean
  +validaAnnoPubblicazione(anno: int): boolean
  +validaNomeCognome(nome: String, cognome: String): boolean
}

class MessaggiInterfaccia {
  +String SUCCESSO_AGGIUNTA_LIBRO
  +String SUCCESSO_PRESTITO
  +String ERRORE_LIMITE_PRESTITO
  +String ERRORE_ISBN_DUPLICATO
  +String ERRORE_MATRICOLA_DUPLICATA
  +String ERRORE_ASSENZA_COPIE
  +String INPUT_EMAIL_NON_VALIDA
  +String INPUT_NOME_NON_VALIDO
  +String INPUT_COGNOME_NON_VALIDO
  +String ANNO_NON_VALIDO
  +String INPUT_MATRICOLA_NON_VALIDO
  +String RITARDO_SEGNALATO
  +String AVVISO_CARICAMENTO_FALLITO
  +String CREDENZIALI_NON_VALIDE
}

class Main{
  -controller: GUIController
  +start(primaryStage: Stage): void
  +stop(): void
  +main(args: String[]): void 
}

' Interfacce (come da tue specifiche)
interface IAutenticatore <<Interface>>
interface IArchivioDati <<Interface>>
interface ILogger <<Interface>>

AuditTrail ..|> ILogger
FileArchivio ..|> IArchivioDati
FileAutenticatore ..|> IAutenticatore

Catalogo "1" *--> "0..*" Libro
Anagrafica "1" *--> "0..*" Utente
RegistroPrestiti "1" *--> "0..*" Prestito
RegistroPrestiti "1" --> "1" Catalogo
RegistroPrestiti "1" --> "1" Anagrafica

Prestito "1" --> "1" Libro 
Utente "1" -- "0..3" Prestito

GUIController "1" --> "1" Catalogo
GUIController "1" --> "1" Anagrafica
GUIController "1" --> "1" RegistroPrestiti
GUIController "1" --> "1" ValidatoreDati
GUIController "1" --> "1" IArchivioDati
GUIController "1" --> "1" IAutenticatore
GUIController "1" --> "1" ILogger

AuditTrail "1" --> "1" IArchivioDati
FileArchivio "1" --> "1" ILogger
FileAutenticatore "1" --> "1" IArchivioDati

GUIView "1" --> "1" GUIController
GUIView ..> MessaggiInterfaccia
GUIView ..> Libro
GUIView ..> Prestito
GUIView ..> Utente

Main ..> GUIView
Main ..> GUIController
@enduml