@startuml
' Definizioni delle Classi
class Libro {
  -isbn: String 
  -titolo: String 
  -autore: List<String> 
  -anno: int 
  -copieTotali: int 
  -copieDisponibili: int 
  +Libro(isbn: String, titolo: String, autore: List<String>, anno: int, copieTotali: int)
  +getIsbn(): String
  +getTitolo(): String
  +getAutore(): List<String>
  +getCopieDisponibili(): int
  +incrementaDisponibilita(): void
  +decrementaDisponibilita(): void
  +isDisponibile(): boolean
}

class Utente {
  -matricola: String 
  -nome: String 
  -cognome: String 
  -email: String 
  +Utente(matricola: String, nome: String, cognome: String, email: String)
  +getMatricola(): String
  +getCognome(): String
  +aggiungiPrestito(p: Prestito): void
  +rimuoviPrestito(p: Prestito): void
  +verificaLimite(max: int): boolean
}

class Prestito {
  -idPrestito: int
  -libro: Libro 
  -utente: Utente 
  -dataInizioPrestito: LocalDate 
  -dataRestituzionePrevista: LocalDate 
  -dataRestituzioneEffettiva: LocalDate 
  -InRitardo: boolean
  +Prestito(idPrestito: int, libro: Libro, utente: Utente, dataInizioPrestito: LocalDate, dataRestituzionePrevista: LocalDate)
  +getIdPrestito(): int
  +getLibro(): Libro
  +getUtente(): Utente
  +chiudiPrestito(dataEffettiva: LocalDate): void
  +verificaRitardo(): boolean
  +segnaRitardo(): void
}

class Catalogo {
  -collezioneLibri: Map<String, Libro> 
  +Catalogo()
  +aggiungiLibro(l: Libro): boolean
  +rimuoviLibro(isbn: String): boolean
  +modificaLibro(isbn: String, nl: Libro): boolean
  +getLibro(isbn: String): Libro
  +ricerca(query: String, campo: String): List<Libro>
  +visualizzaOrdinata(): List<Libro>
}

class Anagrafica {
  -registroUtenti: Map<String, Utente> 
  +Anagrafica()
  +aggiungiUtente(u: Utente): boolean
  +rimuoviUtente(matricola: String): boolean
  +modificaUtente(matricola: String, u: Utente): boolean
  +getUtente(matricola: String): Utente
  +cercaUtente(query: String, campo: String): List<Utente>
  +visualizzaOrdinata(): List<Utente>
}

class RegistroPrestiti {
  -catalogo: Catalogo 
  -anagrafica: Anagrafica
  -prestitiAttivi: List<Prestito> 
  -limitePrestiti: int 
  +RegistroPrestiti(catalogo: Catalogo, anagrafica: Anagrafica)
  +registraPrestito(isbn: String, matr: String, dataPrev: LocalDate): Prestito
  +registraRestituzione(idPrestito: int, dataEFF: LocalDate): boolean
  +getPrestitiAttivi(): List<Prestito>
  +getPrestitiAttivi(u: Utente): List<Prestito>
  +getPrestitiInRitardo(): List<Prestito>
  +haPrestitiAttivi(matr: String): boolean
  +trovaPrestito(idPrestito: int): Prestito
}

class GUIController {
  -catalogo: Catalogo 
  -anagrafica: Anagrafica 
  -registro: RegistroPrestiti 
  -archivio: IArchivioDati
  -valida: ValidatoreDati
  -logger: ILogger
  -autenticatore: IAutenticatore
  +GUIController(archivio: IArchivioDati, logger: ILogger, autenticatore: IAutenticatore, catalogo: Catalogo, anagrafica: Anagrafica, registro: RegistroPrestiti, valide: ValidatoreDati)
  +avviaSistema(): boolean
  +chiudiSistema(): boolean
  +aggiungiUtente(u: Utente): boolean
  +aggiungiLibro(l: Libro): boolean
  +modificaUtente(matrOriginale: String, uNuovo: Utente): boolean
  +modificaLibro(isbnOriginale: String, lNuovo: Libro): boolean
  +cercaLibro(query: iStrng, campo: String): List<Libro>
  +cercaUtente(query: iStrng, campo: String): List<Utente>
  +rimuoviUtente(matr: String): boolean
  +rimuoviLibro(isbn: String): boolean 
  +gestisciPrestito(isbn: String, matr: String, dataPrevistaRestituzione: LocalDate): boolean
  +gestisciRestituzione(idPrestito: int, dataEffettivaRestituzione: LocalDate): boolean
  +ottieniReportPrestiti(): List<Prestito>
  +ottieniCatalogoOrdinato(): List<Libro>
  +ottieniAnagraficaOrdinato(): List<Utente>
  +gestisciLogin(user: String, pass: String): boolean
}

class GUIView{
   -sistema: GUIController
   -messaggi: MessaggiInterfaccia
   +GUIView(sistema: GUIController)
   +avviaInterfaccia(): void
   +gestisciAggiuntaLibro(): void
   +gestisciAggiuntaUtente(): void
   +gestisciModificaLibro(): void
   +gestisciModificaUtente(): void
   +gestisciEliminazioneUtente(): void
   +gestisciEliminazioneLibro(): void
   +gestisciRegistrazionePrestito(): void
   +gestisciRestituzionePrestito(): void
   +gestisciRicercaLibro(): void
   +gestisciRicercaUtente(): void
   +mostraListaLibri(lista: List<Libro>): void
   +mostraListaUtenti(lista: List<Utente>: void
   +mostraListaPrestiti(lista: List<Prestito>): void
   +mostraReportUtente(u: Utente): void
   +mostraMessaggio(msg: MessaggiInterfaccia): void
   +mostraFinestraLogin(): void
   +mostraLogDiSistema(log: List<String>): void
}

interface IArchivioDati{
   +salvaStato(dati: Object, nomeFile: String): boolean
   +caricaStato(nomeFile: String): Object
   +verificaEsistenzaFile(nomeFile: String): boolean
}

interface ILogger{
  +registraAzione(azione: String): void
  +caricaLog(): List<String>
  +salvaLog(): void
  +visualizzaLog(): List<String>
}

interface IAutenticatore{
   +verificaCredenziali(user: String, pass: String): boolean
}

class AuditTrail {
  -logRecords: List<String>
  -archivioDati: IArchivioDati
  +AuditTrail(logRecords: List<String>, archivio: IArchivioDati)
  +registraAzione(azione: String): void
  +caricaLog(): List<String>
  +salvaLog(): void
  +visualizzaLog(): List<String>
}

class FileArchivio {
  -pathDati: String
  -logger: ILogger
  +FileArchivio(path: String, logger: ILogger)
  +salvaStato(dati: Object, nomeFile: String): boolean
  +caricaStato(nomeFile: String): Object
  +verificaEsistenzaFile(nomeFile: String): boolean
}

class FileAutenticatore{
    -credentialsFile: String
    -archivioDati: IArchivioDati
    +FileAutenticatore(credentialsFile: String, archivioDati: Archivio)
    +verificaCredenziali(user: String, pass: String): boolean
}

class ValidatoreDati {
  +validaISBN(isbn: String): boolean
  +validaMatricola(matr: String)
  +validaEmail(email: String)
  +validaAnnoPubblicazione(anno: int)
  +validaNomeCognome(str: String)
}

class MessaggiInterfaccia {
  +String SUCCESSO_AGGIUNTA_LIBRO
  +String SUCCESSO_PRESTITO
  +String ERRORE_LIMITE_PRESTITO
  +String ERRORE_ISBN_DUPLICATO
  +String ERRORE_MATRICOLA_DUPLICATA
  +String ERRORE_ASSENZA_COPIE
  +String INPUT_EMAIL_NON_VALIDA
  +String INPUT_NOME_NON_VALIDO
  +String INPUT_COGNOME_NON_VALIDO
  +String ANNO_NON_VALIDO
  +String INPUT_MATRICOLA_NON_VALIDO
  +String RITARDO_SEGNALATO
  +String AVVISO_CARICAMENTO_FALLITO
  +String CREDENZIALI_NON_VALIDE
}

class Main{
  -controller: GUIController
  +start(primaryStage: Stage): void
  +stop(): void
  +main(args: String[]): void 
}

' Interfacce (come da tue specifiche)
interface IAutenticatore <<Interface>>
interface IArchivioDati <<Interface>>
interface ILogger <<Interface>>

AuditTrail ..|> ILogger
FileArchivio ..|> IArchivioDati
FileAutenticatore ..|> IAutenticatore

Catalogo "1" *--> "0..*" Libro
Anagrafica "1" *--> "0..*" Utente
RegistroPrestiti "1" *--> "0..*" Prestito
RegistroPrestiti "1" --> "1" Catalogo
RegistroPrestiti "1" --> "1" Anagrafica

Prestito "1" --> "1" Libro 
Utente "1" -- "0..3" Prestito

GUIController "1" --> "1" Catalogo
GUIController "1" --> "1" Anagrafica
GUIController "1" --> "1" RegistroPrestiti
GUIController "1" --> "1" ValidatoreDati
GUIController "1" --> "1" IArchivioDati
GUIController "1" --> "1" IAutenticatore
GUIController "1" --> "1" ILogger

AuditTrail "1" --> "1" IArchivioDati
FileArchivio "1" --> "1" ILogger
FileAutenticatore "1" --> "1" IArchivioDati

GUIView "1" --> "1" GUIController
GUIView ..> MessaggiInterfaccia
GUIView ..> Libro
GUIView ..> Prestito
GUIView ..> Utente

Main ..> GUIView
Main ..> GUIController
@enduml